plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.sayan0401biswas.portfolio'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.sayan0401biswas.portfolio'
        minSdk 23
    targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        release {
            def keystorePath = System.getenv('ANDROID_KEYSTORE_PATH')
            if (keystorePath != null) {
                storeFile file(keystorePath)
                storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD')
                keyAlias System.getenv('ANDROID_KEY_ALIAS')
                keyPassword System.getenv('ANDROID_KEY_PASSWORD')
                storeType 'pkcs12'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
